# https://packit.dev/docs/configuration/
specfile_path: phrog.spec
files_to_sync:
  - phrog.spec
  - .packit.yaml
upstream_package_name: phrog
downstream_package_name: phrog
jobs:
  # Build PRs
  - job: copr_build
    trigger: pull_request
    additional_repos:
      - copr://samcday/phosh-nightly
      - copr://samcday/phrog-nightly
    targets:
      - fedora-41-aarch64
      - fedora-41-x86_64
      - fedora-rawhide-aarch64
      - fedora-rawhide-x86_64

  # Build main commits in samcday/phrog-nightly COPR
  - job: copr_build
    trigger: commit
    branch: main
    owner: samcday
    project: phrog-nightly
    additional_repos:
      - copr://samcday/phosh-nightly

  # Build tagged releases in samcday/phrog COPR
  - job: copr_build
    trigger: release
    owner: samcday
    project: phrog
