[package]
name = "phrog"
version = "0.1.0"
edition = "2021"

[dependencies]
glob = "0.3.1"
greetd_ipc = { version = "0.10.0", features = ["sync-codec", "tokio-codec"] }
uzers = { git = "https://github.com/rustadopt/uzers-rs", rev = "8fb29db" }
async-channel = "2.2.1"
anyhow = "1.0.82"
libphosh = { path = "libphosh-rs/libphosh" }

# for fakegreet
thiserror = "1.0"
tokio = { version = "1.5", features = ["process", "macros", "time", "net", "rt"] }
serde = { version = "1.0", features = ["derive"] }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.gtk]
version = '0.18'
branch = "0.18"
git = "https://github.com/gtk-rs/gtk3-rs.git"
features = ['v3_24']

[dependencies.libhandy]
git = "https://gitlab.gnome.org/World/Rust/libhandy-rs"

[build-dependencies]
glib-build-tools = "0.18.0"
