[package]
name = "phrog"
version = "0.1.4"
edition = "2021"

[dependencies]
glob = "0.3.1"
greetd_ipc = { version = "0.10.0", features = ["sync-codec"] }
uzers = "0.12"
async-channel = "2.2.1"
anyhow = "1.0.82"
libphosh = { path = "libphosh-rs/libphosh" }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.gtk]
version = '0.18'
features = ['v3_24']

[dependencies.libhandy]
version = "0.11"

[build-dependencies]
glib-build-tools = "0.18.0"
