[package]
name = "phrog"
version = "0.10.0"
edition = "2021"

[dependencies]
glob = "0.3.1"
greetd_ipc = { version = "0.10.0", features = ["sync-codec"] }
async-channel = "2.2.1"
anyhow = "1.0.82"
libphosh = { path = "libphosh-rs/libphosh" }
clap = { version = "4.5.4", features = ["derive"] }
wayland-client = "0.31.3"
zbus = { version = "4", default-features = false, features = ["blocking", "async-io"] }
nix = { version = "0.29.0", features = ["signal"] }
async-global-executor = "2.4.1"
futures-util = "0.3.30"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.gtk]
version = "0.18"
features = ["v3_24"]

[dependencies.libhandy]
version = "0.11"
features = ["v1_6"]

[build-dependencies]
glib-build-tools = "0.18.0"

[dev-dependencies]
input-event-codes = "6.2.0"
wayland-client = "0.31.3"
wayland-protocols = { version = "0.32.1", features = ["client"] }
wayland-protocols-misc = { version = "0.3.1", features = ["client"] }
wayland-protocols-wlr = { version = "0.3.1", features = ["client"] }
tempdir = "0.3.7"

[features]
keypad-shuffle = []
static = ["libphosh/static", "keypad-shuffle"]
