[options]
library = "PhoshDM"
version = "0"
min_cfg_version = "0"
target_path = "."
girs_directories = ["../gir-files/", "../"]
work_mode = "sys"
single_version_file = true

external_libraries = [
    "GLib",
    "GObject",
]
split_build_rs = true
