[terminal]
vt = 7

# The default session, also known as the greeter.
[default_session]
command = "systemd-cat --identifier=phrog /usr/bin/phrog"
# The user the phrog runs as. Make sure the users home directory is writable.
#user = "_greetd"
