name: alpine-apk

on:
  push:
    branches: [main]
    paths:
      - 'APKBUILD'
      - '.github/workflows/alpine.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jirutka/setup-alpine@v1
        with:
          branch: edge
      - name: install deps
        run: |
          apk add alpine-sdk
          abuild -F deps
        shell: alpine.sh --root {0}
      - name: build package
        run: |
          abuild-keygen -n -a -i
          abuild -F
        shell: alpine.sh --root {0}
