name: Build app

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        sudo apt-get -y build-dep ./phosh

        git clone https://gitlab.gnome.org/World/Phosh/gmobile.git
        cd gmobile
        git checkout v0.2.0
        meson setup _build .
        sudo meson install -C _build

        export SYSTEM_DEPS_LIBPHOSH_0_BUILD_INTERNAL=auto
        cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
