name: x86-64

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  SYSTEM_DEPS_LIBPHOSH_0_BUILD_INTERNAL: auto

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      # selecting a toolchain either by action or manual `rustup` calls should happen
      # before the plugin, as the cache uses the current rustc version as its cache key
      - run: rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@v2
        with: {}
      # for phrog tests
      - name: apt-get deps
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: phosh phoc xvfb wf-recorder
          version: 1.0
      - name: apt-get build-dep ./phosh
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get -y build-dep ./phosh
      - name: build gmobile (should be temporary)
        run: |
          git clone https://gitlab.gnome.org/World/Phosh/gmobile.git
          cd gmobile
          git checkout v0.2.0
          meson setup --prefix=/usr _build .
          sudo meson install -C _build
      - name: Build
        run: |
          cargo build --all-targets --verbose
      - name: Test
        run: |
          # Install phrog schemas so the tests can run.
          mkdir -p $HOME/.local/share/glib-2.0/schemas/
          cp resources/com.samcday.phrog.gschema.xml $HOME/.local/share/glib-2.0/schemas/
          glib-compile-schemas $HOME/.local/share/glib-2.0/schemas/

          dbus-run-session xvfb-run -a -s -noreset phoc -E "wf-recorder -f tests.mp4" &
          trap "pkill phoc; sleep 1" EXIT

          # wait a moment for compositor startup. would be better to properly parse out the
          # display name and readiness state from phoc stdout.
          sleep 1
          WAYLAND_DISPLAY=wayland-0 cargo test --verbose -- --test-threads=1 --nocapture
      - uses: actions/upload-artifact@v4
        with:
          name: x86-64-debug
          path: target/debug/phrog
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: tests-recording
          path: tests.mp4
