name: Build app

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        sudo apt-get -y build-dep ./phosh
        export SYSTEM_DEPS_LIBPHOSH_0_BUILD_INTERNAL=auto
        cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
