name: debian

on:
  workflow_dispatch: {}
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  debian:
    runs-on: ubuntu-24.04
    container: debian:trixie
    steps:
      - uses: actions/checkout@v4
